//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VHD_Director.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VHD_Director.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap boot_25_22_trans {
            get {
                object obj = ResourceManager.GetObject("boot_25_22_trans", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap burn_black {
            get {
                object obj = ResourceManager.GetObject("burn-black", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap burn_disc_512 {
            get {
                object obj = ResourceManager.GetObject("burn-disc-512", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap burn_green {
            get {
                object obj = ResourceManager.GetObject("burn-green", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap burn_red {
            get {
                object obj = ResourceManager.GetObject("burn-red", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap burn_yellow {
            get {
                object obj = ResourceManager.GetObject("burn-yellow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {\rtf1\ansi\ansicpg65001\cocoartf1038\cocoasubrtf360
        ///{\fonttbl\f0\fnil\fcharset0 SegoeUI;}
        ///{\colortbl;\red255\green255\blue255;\red0\green0\blue0;\red109\green109\blue109;}
        ///{\*\listtable{\list\listtemplateid1\listhybrid{\listlevel\levelnfc23\levelnfcn23\leveljc0\leveljcn0\levelfollow0\levelstartat1\levelspace360\levelindent0{\*\levelmarker \{disc\}}{\leveltext\leveltemplateid1\&apos;01\uc0\u8226 ;}{\levelnumbers;}\fi-360\li720\lin720 }{\listname ;}\listid1}
        ///{\list\listtemplateid2\listhybrid{\listlevel\levelnfc23 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CompactVirtualDisk {
            get {
                return ResourceManager.GetString("CompactVirtualDisk", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap createvhd {
            get {
                object obj = ResourceManager.GetObject("createvhd", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap dead_identicon {
            get {
                object obj = ResourceManager.GetObject("dead_identicon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Drag_n_Drop_Cut {
            get {
                object obj = ResourceManager.GetObject("Drag\'n\'Drop-Cut", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap dragondrop_1_ {
            get {
                object obj = ResourceManager.GetObject("dragondrop[1]", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap fragmented_22_trans {
            get {
                object obj = ResourceManager.GetObject("fragmented_22_trans", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GreenPartition_Fill {
            get {
                object obj = ResourceManager.GetObject("GreenPartition_Fill", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GreenPartition_Fill_Unused {
            get {
                object obj = ResourceManager.GetObject("GreenPartition_Fill_Unused", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GreenPartition_Left {
            get {
                object obj = ResourceManager.GetObject("GreenPartition_Left", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap GreenPartition_Right {
            get {
                object obj = ResourceManager.GetObject("GreenPartition_Right", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Icon hdd {
            get {
                object obj = ResourceManager.GetObject("hdd", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Icon hdd_2 {
            get {
                object obj = ResourceManager.GetObject("hdd_2", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap InnerFill {
            get {
                object obj = ResourceManager.GetObject("InnerFill", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap InnerLeft {
            get {
                object obj = ResourceManager.GetObject("InnerLeft", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap InnerRight {
            get {
                object obj = ResourceManager.GetObject("InnerRight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap MagnifyingGlass_32_web {
            get {
                object obj = ResourceManager.GetObject("MagnifyingGlass_32_web", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap MagnifyingGlass_64_web {
            get {
                object obj = ResourceManager.GetObject("MagnifyingGlass_64_web", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap MagnifyingGlass_96_64_centered {
            get {
                object obj = ResourceManager.GetObject("MagnifyingGlass_96_64_centered", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap OuterFill {
            get {
                object obj = ResourceManager.GetObject("OuterFill", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap OuterLeft {
            get {
                object obj = ResourceManager.GetObject("OuterLeft", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap OuterRight {
            get {
                object obj = ResourceManager.GetObject("OuterRight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PartitionBar_Fill {
            get {
                object obj = ResourceManager.GetObject("PartitionBar_Fill", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PartitionBar_Fill_Unused {
            get {
                object obj = ResourceManager.GetObject("PartitionBar_Fill_Unused", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PartitionBar_Left {
            get {
                object obj = ResourceManager.GetObject("PartitionBar_Left", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap PartitionBar_Right {
            get {
                object obj = ResourceManager.GetObject("PartitionBar_Right", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ring_48 {
            get {
                object obj = ResourceManager.GetObject("ring_48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static byte[] ROYALP {
            get {
                object obj = ResourceManager.GetObject("ROYALP", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static byte[] SampleIconsInPlace {
            get {
                object obj = ResourceManager.GetObject("SampleIconsInPlace", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        internal static System.Drawing.Bitmap shadow_box_40x40_for_32x32 {
            get {
                object obj = ResourceManager.GetObject("shadow_box_40x40_for_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
