namespace Microsoft.Storage.Vds.Interop
{
    using System;

    public enum VDS_ASYNC_OUTPUT_TYPE
    {
        VDS_ASYNCOUT_ADDLUNPLEX = 0x34,
        VDS_ASYNCOUT_ADDPORTAL = 0x41,
        VDS_ASYNCOUT_ADDVOLUMEPLEX = 4,
        VDS_ASYNCOUT_BREAKLUNPLEX = 0x33,
        VDS_ASYNCOUT_BREAKVOLUMEPLEX = 5,
        VDS_ASYNCOUT_CLEAN = 11,
        VDS_ASYNCOUT_CREATELUN = 50,
        VDS_ASYNCOUT_CREATEPARTITION = 10,
        VDS_ASYNCOUT_CREATEPORTALGROUP = 0x3f,
        VDS_ASYNCOUT_CREATETARGET = 0x3e,
        VDS_ASYNCOUT_CREATEVOLUME = 1,
        VDS_ASYNCOUT_DELETEPORTALGROUP = 0x43,
        VDS_ASYNCOUT_DELETETARGET = 0x40,
        VDS_ASYNCOUT_EXTENDLUN = 0x36,
        VDS_ASYNCOUT_EXTENDVOLUME = 2,
        VDS_ASYNCOUT_FORMAT = 0x65,
        VDS_ASYNCOUT_LOGINTOTARGET = 60,
        VDS_ASYNCOUT_LOGOUTFROMTARGET = 0x3d,
        VDS_ASYNCOUT_RECOVERLUN = 0x38,
        VDS_ASYNCOUT_RECOVERPACK = 8,
        VDS_ASYNCOUT_REMOVELUNPLEX = 0x35,
        VDS_ASYNCOUT_REMOVEPORTAL = 0x42,
        VDS_ASYNCOUT_REMOVEVOLUMEPLEX = 6,
        VDS_ASYNCOUT_REPAIRVOLUMEPLEX = 7,
        VDS_ASYNCOUT_REPLACEDISK = 9,
        VDS_ASYNCOUT_SHRINKLUN = 0x37,
        VDS_ASYNCOUT_SHRINKVOLUME = 3,
        VDS_ASYNCOUT_UNKNOWN = 0
    }
}

